完整的咒法学
VM-Chinese-translate-group/FTB-Arcanum-Institute-Chinese pull request #27
Opened 2024-01-31 05:48 UTC by mangke01

2024-01-31 07:08 UTC, Wulian233 requested changes

2024-01-31 07:08 UTC, Wulian233 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/magic_spells_and_more.snbt
> +				"[\"\",\"右侧是\",{\"text\":\"[在线Wiki]\",\"color\":\"yellow\",\"clickEvent\":{\"action\":\"open_url\",\"value\":\"https://object-object.github.io/HexMod/v/latest/1.18/en_us/\"},\"hoverEvent\":{\"act
```suggestion
				"[\"\",\"右侧是\",{\"text\":\"[在线中文教程]\",\"color\":\"yellow\",\"clickEvent\":{\"action\":\"open_url\",\"value\":\"https://hexcasting.hexxy.media/v/latest/1.18/zh_cn/\"},\"hoverEvent\":{\"action\":\"show_text\",\"contents\":[{\"text\":\"https://hexcasting.hexxy.media/v/latest/1.18/zh_cn/\",\"underlined\":true,\"color\":\"aqua\"}]}},\"这上面的内容应该很有用！并且上面的图片还有动画\",{\"text\":\"还有动画\",\"color\":\"gold\"},\"！\"]"
```

2024-02-01 01:17 UTC, nageih approved these changes

2024-02-01 01:17 UTC, nageih commented on Patch-Pack-CN/config/ftbquests/quests/chapters/magic_spells_and_more.snbt
> +				"每种促动石的触发条件都不一样：\\n\\n• &b工具匠促动石&r右键触发。\\n\\n• &b制箭师促动石&r在被注视一段时间后被触发。\\n\\n• &b牧师促动石&r要复杂一点"
```suggestion
				"每种促动石的触发条件都不一样：\\n\\n• &b工具匠促动石&r被右击后触发。\\n\\n• &b制箭师促动石&r在被注视一段时间后被触发。\\n\\n• &b牧师促动石&r要复杂一点"
```

2024-02-01 01:17 UTC, merged